// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr0Wya3xaFZEaNcDRfFCRZ4ZPTHRZr8ps',
    appId: '1:532653842811:web:a883091368f420830b9dde',
    messagingSenderId: '532653842811',
    projectId: 'birthday-calendar-57a54',
    authDomain: 'birthday-calendar-57a54.firebaseapp.com',
    storageBucket: 'birthday-calendar-57a54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX3bLjwAol9AWSepkty7iw6EbQNpci6Ho',
    appId: '1:532653842811:android:232bb9a33a1e050d0b9dde',
    messagingSenderId: '532653842811',
    projectId: 'birthday-calendar-57a54',
    storageBucket: 'birthday-calendar-57a54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqH68rmoP0exdKwRXUtJq2K61SweiqS3w',
    appId: '1:532653842811:ios:98cc34bf079088d70b9dde',
    messagingSenderId: '532653842811',
    projectId: 'birthday-calendar-57a54',
    storageBucket: 'birthday-calendar-57a54.firebasestorage.app',
    iosBundleId: 'com.example.birthdayCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqH68rmoP0exdKwRXUtJq2K61SweiqS3w',
    appId: '1:532653842811:ios:98cc34bf079088d70b9dde',
    messagingSenderId: '532653842811',
    projectId: 'birthday-calendar-57a54',
    storageBucket: 'birthday-calendar-57a54.firebasestorage.app',
    iosBundleId: 'com.example.birthdayCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr0Wya3xaFZEaNcDRfFCRZ4ZPTHRZr8ps',
    appId: '1:532653842811:web:5979ccbf31f9b17d0b9dde',
    messagingSenderId: '532653842811',
    projectId: 'birthday-calendar-57a54',
    authDomain: 'birthday-calendar-57a54.firebaseapp.com',
    storageBucket: 'birthday-calendar-57a54.firebasestorage.app',
  );
}
